[김산] Mission 2: 모델링
wecode-bootcamp-korea/30-westagram-backend-4-team pull request #14
Opened 2022-02-17 08:38 UTC by cloudhat

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- models.py 에 user클래스 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 문제에서 요구한 이름, 이메일 등의 속성 구현
- 각 속성에 blank, null 값 지정

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-02-17 08:41 UTC, kyeongraekim requested changes
아래 내용 확인하고 수정해주세요~

2022-02-17 08:41 UTC, kyeongraekim commented on students/kimsan/users/models.py
> +    class Meta:
라인 공백 한 줄이 더 필요해 보입니다!~

2022-02-17 08:41 UTC, kyeongraekim commented on students/kimsan/users/models.py
> +    extra_info  =models.TextField( blank=True, null=True)
모든 내용에 blank=True & null=True를 넣으면 문제가 되어 보입니다.
blank=True 와 null= True의 역할과 의미를 리서치 해보신 후에 필요한 부분에만 넣어주세요!

2022-02-17 08:41 UTC, kyeongraekim commented on students/kimsan/users/models.py
> +    phone_number=models.IntegerField( blank=True, null=True)
변수 선언 이후 = 에는 띄어쓰기가 한 칸 필요합니다.

2022-02-17 08:41 UTC, kyeongraekim commented on students/kimsan/users/models.py
> +    extra_info  =models.TextField( blank=True, null=True)
영어 전체원어를 풀어서 써주셔야 합니다. information으로 제 3자의 가독성을 위해서 늘려 써주세요!~

2022-02-17 09:48 UTC, kyeongraekim requested changes
산님 여러번 엎은 후 진행하시느라 고생많으십니다!~ 아래 내용 추가 수정 반영 부탁드릴게요!~

2022-02-17 09:48 UTC, kyeongraekim commented on students/kimsan/users/models.py
> +    first_name        = models.CharField(max_length=20 )
20 뒤 소괄호를 닫아주실 때 불필요한 공백이 한칸 보이네요!~

2022-02-17 09:48 UTC, kyeongraekim commented on students/kimsan/users/models.py
> +    phone_number      = models.IntegerField( )
인티져 필드에 아무런 속성 값을 넣어 주실게 없다면 굳이 한칸의 공백을 안에 넣으실 필요는 없습니다!~

2022-02-17 09:48 UTC, kyeongraekim commented on students/kimsan/users/models.py
> +    email             = models.CharField(max_length=100)
email field에 unique 속성을 추가하셔서 유저가 중복 저장되는 문제가 발생하지 않도록 수정해주세요!
공식 문서에서 그 방법을 찾아보고 적용해주세요.

2022-02-17 09:48 UTC, kyeongraekim commented on students/kimsan/users/models.py
> +
데이터의 이력 관리를 위해서 created_at, updated_at column을 추가해주세요.
```python
created_at = models.DateTimeField(auto_now_add=True)
updated_at = models.DateTimeField(auto_now=True)

2022-02-18 01:32 UTC, cloudhat commented on students/kimsan/users/models.py
> +    extra_info  =models.TextField( blank=True, null=True)
네 변경했습니다!

2022-02-18 01:32 UTC, cloudhat commented on students/kimsan/users/models.py
> +    first_name        = models.CharField(max_length=20 )
네 수정했스빈다!

2022-02-18 04:58 UTC, kyeongraekim approved these changes
LGTM!~

2022-02-18 04:58 UTC, merged