[김산] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/30-westagram-backend-4-team pull request #17
Opened 2022-02-18 07:11 UTC by cloudhat

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 기능 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 ,전화번호, 비밀번호에 정규표현식 적용
- 이메일에 unique속성 적용하여 예외처리

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-02-18 07:45 UTC, kyeongraekim requested changes
아래 내용 확인하여 수정해주세요!~

2022-02-18 07:45 UTC, kyeongraekim commented on students/kimsan/users/urls.py
> +    path('/sign_up', UserView.as_view()),
URL 작성시 under bar 사용은 Restful 하지 못한 설계법이여서 지양해야 합니다. 언더바를 제거하거나 하이픈을 대신 사용해주세요~

2022-02-18 07:45 UTC, kyeongraekim commented on students/kimsan/users/urls.py
> +#cd westagram/30-westagram-backend-4-team/students/kimsan
불필요한 주석은 제거해주세요! 실제 상용화될 서비스의 배포 브랜치에 푸시한다는 생각으로 제 3자의 코드 독해 흐름을 방해하는 불필요한 코드는 늘 제거하는 습관을 길러주세요~

2022-02-18 07:45 UTC, kyeongraekim commented on students/kimsan/users/views.py
> +# invalid input http -v POST 127.0.0.1:8080/users/sign_up first_name='김' second_name='산' email='email4n@naver.com' password="azA__++--3" phone_number='010-1234-5678'
이곳도 불필요한 코드 주석으로 보여집니다.

2022-02-18 07:45 UTC, kyeongraekim commented on students/kimsan/users/views.py
> +            regex_password     = re.compile('[\W\w]{8}[\W\w]+')
- 정규표현식을 사용할 경우, 자주 사용되는 경우가 아니라면 `compile()`해서 사용하지 않고, `match()`를 사용하는 것을 공식 문서에서 추천하고 있습니다.  해당 정규표현식에서 complie 용법이 꼭 필 요한 지 한 번 고민해보세요!~
- 정규표현식은 상수이기 때문에 파이썬 컨벤션에 맞게 대문자로 설정해주세요!~
- 그리고 시간이 된다면 해당 내용을 다른 파일로 따로 빼서 본 View File에서 필요한 함수를 import 하여 사용하는  모듈화 작업을 한번 도전해보세요!

2022-02-18 07:45 UTC, kyeongraekim commented on students/kimsan/users/views.py
> +            #database에 저장
코드 상에서 충분히 이해가  가능한 불필요한 주석은 제거해주세요!

2022-02-18 07:45 UTC, kyeongraekim commented on students/kimsan/users/views.py
> +            User.objects.create(first_name=first_name, second_name=second_name, email=email, password=password ,phone_number=phone_number)
해당 내용도 위코드 컨벤션에 맞게 제 3자의 가독성을 위해 보기 쉽게 정렬해주세요.

2022-02-18 07:45 UTC, kyeongraekim commented on students/kimsan/users/views.py
> +
핸들링 하는 에러 중 키에러는 보이지 않네요? 위 코드에서 키에러가 날 수 있는 상황을 아래 코멘트로 남겨주시고 에러 except 에 추가해주세요!~

2022-02-18 08:08 UTC, cloudhat commented on students/kimsan/users/views.py
> +
request messege의 key 값이 서버의 key 와 일치하지 않을 경우 발생합니다

2022-02-18 09:45 UTC, kyeongraekim requested changes
아래 내용 확인하여 수정해주세요!~ 마지막 수정 부분이 될 것 같네요!

2022-02-18 09:45 UTC, kyeongraekim commented on students/kimsan/users/validation.py
> +        return True
해당 내용은 if-else 구조로의 불필요한 분기가 불필요 합니다. if 문 하나로만 처리할 수 있게 한 번 수정해보세요!

2022-02-18 09:45 UTC, kyeongraekim commented on students/kimsan/users/views.py
> +            if validate_email(email)==False:
if == False 의 구조보다 더 연산면에서 효율적인 if not 의 구조로 수정해보세요!
그러면 validation.py 에서의 리턴값과의 상호 호응을 봐야겠지요?

2022-02-21 01:22 UTC, cloudhat commented on students/kimsan/users/validation.py
> +        return True
넵 수정했습니다. 저는 가독성을 고려해 리턴 값을 True, False 값으로 바꾸었는데 이 방식이 오히려 가독성을 해치는 것인지 궁금합니다.

2022-02-21 01:23 UTC, kyeongraekim requested changes
다음의 내용 조금만 더 수정해서 푸시해주세요!~

2022-02-21 01:23 UTC, kyeongraekim commented on students/kimsan/users/validation.py
> +    return re.match('[\W\w]{8}[\W\w]+',password)
해당 비밀번호의 정규표현식이 비밀번호를 가르기에는 다소 부족해보이네요!
해당 정규표현식으로 설정되는 유효성 검증 기준은 무엇인가요? 다른 방향성을 한 번 고민해보세요!~

2022-02-21 01:23 UTC, kyeongraekim commented on students/kimsan/users/views.py
> +class UserView(View):
SignUpView로 클래스를 따로 나누는 것을 권장드립니다. 하나의 유저 뷰안에 두 개의 회원가입/ 로그인 뷰를 분기하게 되면 둘 중 하나의 기능을 수정해야 할 때 불가피하게 전체 클래스를 건드는 효과를 가지게 됩니다. 분리성과 향후 확장성을 위해 클래스를 나눠보는것은어떨까요?

2022-02-21 01:25 UTC, cloudhat commented on students/kimsan/users/views.py
> +            if validate_email(email)==False:
수정했습니다 어떤 이유에서 후자가 더 효율적인지도 조사해보겠습니다:)

2022-02-21 03:27 UTC, cloudhat commented on students/kimsan/users/validation.py
> +    return re.match('[\W\w]{8}[\W\w]+',password)
네 정규식 수정했습니다

2022-02-21 04:19 UTC, cloudhat commented on students/kimsan/users/views.py
> +class UserView(View):
클래스명 변경하였습니다

2022-02-21 05:08 UTC, kyeongraekim approved these changes
LGTM!~

2022-02-21 05:09 UTC, merged