[김기현] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/30-westagram-backend-4-team pull request #19
Opened 2022-02-18 09:00 UTC by tanonkim

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 계정이나 패스워드 키가 전달되지 않았을 경우 메시지 반환 구현
- 계정 및 비밀번호를 잘못 입력한 경우 에러메시지 반환 구현
- 로그인이 성공할 시 성공 메시지 반환 구현
- URLconf 정의 완료
- httpie로 로그인 실행 작동 확인

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-02-18 09:06 UTC, cloudhat commented on students/kihyeon/users/views.py
> +                password   = data['password']
코드 컨벤션에 맞게 정렬 부탁드려요!
https://study.wecode.co.kr/session/content/180

2022-02-18 09:13 UTC, cloudhat commented on students/kihyeon/users/views.py
> +                password   = data['password']
51~55줄에서 email과 password가 db에 있는지 검증하는데 굳이 왜 57줄에서 user_verify 변수를 사용하여 또 검증하는지 궁금합니다. 만약 불필요한 검증일 경우 속도에서 손해볼 것 같습니다. exists()를 할 때 db를 조회하기 때문입니다.

2022-02-18 11:08 UTC, tanonkim commented on students/kihyeon/users/views.py
> +                password   = data['password']
불필요한 검증임을 확인했고 수정완료했습니다!

2022-02-19 09:25 UTC, Pbang91 commented on students/kihyeon/users/views.py
기현님 email에 해당하는 password와 비교하는 건 어떨까요? 같은 비밀번호로 설정한 사람이 두명일 수도 있지 않을까요ㅎㅎㅎ???

2022-02-19 14:48 UTC, sjoon21 commented on students/kihyeon/users/views.py
> +                return JsonResponse({'MESSAGE' : 'INVALIDUSER : Wrongpassword'}, status=401)
안녕하세요 기현님! 올리신 코드 잘봤습니다. 이메일과 비밀번호가 일치하지 않을때 `{'MESSAGE' : 'INVALIDUSER : Wrongemail'}` 와 `{'MESSAGE' : 'INVALIDUSER : Wrongpassword'}`를 하신 이유가 있을실까요? Invalid user와 invalid password로 간결하게 표현하시고 두 단어가 합칠때 스네이크 표기법을 쓰시면 조금 더 가독성이 좋은 메세지가 될 것 같습니다.

2022-02-20 07:58 UTC, tanonkim commented on students/kihyeon/users/views.py
> +                return JsonResponse({'MESSAGE' : 'INVALIDUSER : Wrongpassword'}, status=401)
아무리 생각해도 이상해서 다시 수정했습니다!!! ☺️
좋은 리뷰 감사합니다🔥🔥

2022-02-20 08:30 UTC, tanonkim commented on students/kihyeon/users/views.py
건규님이 말씀하신대로 제 코드의 오류가 있었는데, A의 유저 이메일을 사용하면서 B 유저의 비밀번호가 입력될 때 invalid하다는 메세지를 return해야 하는데 sucess되는 오류를 확인했습니다.

제가 건규님께 피드백한 것처럼 간결하게 코드 수정해서 다시 올렸습니다!!
세밀한 코드검증 감사합니다🔥

2022-02-21 01:24 UTC, kyeongraekim requested changes
아래 내용 추가 수정 부탁드려요!~

2022-02-21 01:24 UTC, kyeongraekim commented on students/kihyeon/users/views.py
> +
모델에 내가 의도한 데이터 객체가 없을 시에 발생하는 에러도 연구해보셔서 한 번 추가 시켜주세요!~

2022-02-21 01:34 UTC, kyeongraekim requested changes
아래 내용 추가 수정 부탁드려요!~

2022-02-21 01:34 UTC, kyeongraekim commented on students/kihyeon/users/views.py
> +            valid_password = data['password']
유저가 작성한 내용이 클라이언트 단에서 바디 data로 넘어온 값이기 때문에 아직 valid 하다고 명명지을 수는 없어 보입니다. 그냥 깔끔하게 email  또는 password로 진행하셔도 무방할 것 같아 보이네요!~

2022-02-21 04:03 UTC, tanonkim commented on students/kihyeon/users/views.py
> +            valid_password = data['password']
수정완료했습니다!!

감사합니다☺️

2022-02-21 04:21 UTC, kyeongraekim approved these changes
LGTM!~

2022-02-21 04:21 UTC, merged