[안성준] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/30-westagram-backend-4-team pull request #20
Opened 2022-02-19 05:29 UTC by sjoon21

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- SignInView 생성
- 로그인 url 생성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일/비밀번호 입력시 로그인 가능: status = 200
- 입력 정보 불일치시 status=401 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-02-19 06:31 UTC, tanonkim reviewed
LGTM ~~~🔥🔥

2022-02-19 09:28 UTC, Pbang91 commented on students/sungjoon/users/views.py
> +        data = json.loads(request.body)
성준님 email이나 password를 누락할 때 지정한 key error가 발생했나요? 저는 지정한 키에러가 안나타나서 try 구문안에 request 를 받아줬더니 그제서야 나오더라구요 ㅎㅎ :  )

2022-02-20 08:45 UTC, tanonkim commented on students/sungjoon/users/views.py
> +                return JsonResponse ({"message" : "INVALID_PASSWORD"}, status=401)
성준님!

여기서 A 유저 이메일에 A사용자의 비밀번호가 일치해야 SUCCESS 반환을 하는데, 해당 코드는 A 사용자의 이메일에 다른 유저의 비밀번호가 들어가도 SUCCESS를 반환하는 코드로 보입니다.

2022-02-21 01:31 UTC, kyeongraekim commented on students/sungjoon/users/views.py
> +                return JsonResponse ({"message" : "INVALID_PASSWORD"}, status=401)
기현님이 잘 잡아 주신 것처럼 이메일 따로 비밀번호 따로 필터를 걸게 되면 A 유저가 (이메일: 123@123.com & 비밀번호: 123) B 유저 (abc@abc.com, abc)의 비밀번호 'abc' 를 실수로 잘못 치게 된 경우에도 각각의 칼럼에서 이메일 따로 비밀번호 따로 인증 검사를 하기 때문에 로그인에 성공하는 불상사가 날 것 같아보이네요!~

2022-02-21 04:58 UTC, sjoon21 commented on students/sungjoon/users/views.py
> +        data = json.loads(request.body)
건규님 오류는 나지 않았지만 미연에 방지하기 위해서 일괄적으로 try 구문안에 넣었습니다! 감사합니다!

2022-02-21 05:00 UTC, sjoon21 commented on students/sungjoon/users/views.py
> +                return JsonResponse ({"message" : "INVALID_PASSWORD"}, status=401)
기현님 경래님 감사합니다.  유저가 가입한 이메일과 비밀번호로만 가능하게 수정했습니다.

2022-02-21 07:20 UTC, kyeongraekim requested changes
아래 내용 확인하여 수정해주세요!~

2022-02-21 07:20 UTC, kyeongraekim commented on students/sungjoon/users/views.py
> +            if not User.objects.get(email = email).password == password:
해당 내용 잘 의도에 맞게 수정해주셨네요. 다만 장고의 filter 메소드의 특성상 .filter(a=a, b=b)의 형식으로도 풀어나가실 수 있습니다. 해당 내용보다 객체를 잡고 해당 객체의 비밀번호를 타고타고 들어가는 내용보다 더 가독성과 코드 진행상 효율적으로 보여지네요!~

2022-02-21 07:56 UTC, kyeongraekim requested changes
아래내용 최종으로 확인 후 수정해주세요~

2022-02-21 07:56 UTC, kyeongraekim commented on students/sungjoon/users/views.py
> +                return JsonResponse ({"message" : "INVALID_USER"}, status=401)
이메일에 유효성 검증이 중복으로 들어가네요? 해당 내용을 어떻게 수정하면 좋을지 고민해보세요!~

2022-02-21 08:00 UTC, sjoon21 commented on students/sungjoon/users/views.py
> +                return JsonResponse ({"message" : "INVALID_USER"}, status=401)
해당 사항 수정하였습니다. 감사합니다.

2022-02-21 08:03 UTC, kyeongraekim approved these changes
LGTM!~

2022-02-21 08:03 UTC, merged