[박건규] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/30-westagram-backend-4-team pull request #21
Opened 2022-02-19 09:22 UTC by Pbang91

fix: modify SignUpView in views.py

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- User 로그인 기능 구현
- SignUp 기능 json request 부분 try 구문 안으로 이동
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 사용자 email로 로그인 기능 구현
- 실패시 에러 반환
- 성공시 200  반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- try 구문안에서 request를 받아줘야 내가 지정한 Key Error를 응답한다는 것을 뒤늦게 깨달아서 수정했습니다 :)..기본에 충실하겠습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-02-19 12:56 UTC, tanonkim commented on students/geongue/users/views.py
> +import email
어떠한 목적으로 email을 import하셨는지 궁금합니다!
만약 실제 코드상에서 사용하지 않는 임포트문이라면 삭제하는게 좋을 것 같습니다!

2022-02-19 12:56 UTC, tanonkim commented on students/geongue/users/views.py
>  from .models      import User
Align을 잘 맞추면 코드가 깔끔하고 정리된 느낌을 줄 수 있을 것 같습니다.
https://study.wecode.co.kr/session/content/180
(2-5 Cdode Align)

2022-02-19 12:56 UTC, tanonkim commented on students/geongue/users/views.py
> +                return JsonResponse({"message" : "INVALID_UESR"}, status = 401)
login_password를 password와 비교해 같지 않다는 if문도 좋아보이지만 
input으로 받은 email과 password로 매칭되는 유저가 존재하는지 한번의 쿼리로 정리할 수 있어보입니다!

변수들을 정리하고
 if not User.objects.filter(email = login_email, password=login_password).eixsts():
로 정리하면 더 효율적이고 가독성이 높아질 것 같습니다.

2022-02-19 14:30 UTC, Pbang91 commented on students/geongue/users/views.py
> +                return JsonResponse({"message" : "INVALID_UESR"}, status = 401)
오! 좋은 생각이에요. 말씀하신 것처럼 수정해서 진행하겠습니다.

2022-02-19 14:30 UTC, Pbang91 commented on students/geongue/users/views.py
>  from .models      import User
꼼꼼하게 살펴주셔서 감사합니다!

2022-02-19 14:30 UTC, Pbang91 commented on students/geongue/users/views.py
> +import email
에고 실수로 해당 내용이 들어간 것 같습니다. 꼼꼼하게 살펴주셔서 감사합니다!

2022-02-19 14:47 UTC, sjoon21 commented on students/geongue/users/views.py
> +                return JsonResponse({"message" : "INVALID_UESR"}, status = 401)
안녕하세요 건규님! `if not email.exists() or login_password != password:` 메세지가 합쳐져 있는 이유가 있을까요? 유저가 Response로 올바르지 않은 비밀번호 때문에 로그인을 못하는지 아니면 이메일을 잘 못 적어서 인지 명확히 알기가 어려운것 같습니다.

2022-02-19 15:54 UTC, Pbang91 commented on students/geongue/users/views.py
> +                return JsonResponse({"message" : "INVALID_UESR"}, status = 401)
email과 password 부분을 나눠서 진행하려다가..구현 요구 사항에 에러 메세지가 "INVALID_USER" 하나로 되어있어서요..우선은 요구사항에 따르자 해서 해당내용으로 진행했습니다. 이 내용 관련해서 월요일에 한번 같이 얘기나누면 좋을 것 같아요!

2022-02-21 01:36 UTC, kyeongraekim requested changes
아래 내용 간단히 수정 부탁드리겠습니다!~

2022-02-21 01:36 UTC, kyeongraekim commented on students/geongue/users/views.py
> +            #password       = email[0].password
불필요한 주석은 제거해주세요!~ 깃헙에 메인에 피알 형태로 올라오는 코드들은 실제 바로 상용화가 되기를 희망하는 소스코드들입니다. 보다 프로페셔널한 마인드셋으로 푸시에 임해주시면 감사하겠습니다!~

2022-02-21 03:45 UTC, Pbang91 commented on students/geongue/users/views.py
> +            #password       = email[0].password
주석처리를 확인하지 않고 push를 진행했습니다. 항상 꼼꼼히 살펴보겠습니다! 감사합니다!

2022-02-21 04:20 UTC, kyeongraekim approved these changes
LGTM!~ 다음과정 이어서 진행해주세요!~

2022-02-21 04:20 UTC, merged