[김기현] Mission 5: 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/30-westagram-backend-4-team pull request #22
Opened 2022-02-21 05:05 UTC by tanonkim

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- bcrypt를 사용한 회원가입 비밀번호 암호화 적용		 

## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
-  회원가입 코드에 비밀번호 암호화를 추가
- database에 암호화 된 비밀번호 저장 확인
<img width="1638" alt="스크린샷 2022-02-21 오후 1 52 38" src="https://user-images.githubusercontent.com/60570733/154892693-78c1525c-39c9-4c4d-9be2-88ada85921b0.png">

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-02-21 05:52 UTC, cloudhat commented on students/kihyeon/users/views.py
>                  first_name   = data["first_name"],
아마 json.body에서 first,last name을 얻는 것 같은데 14~16줄의 email,password,phone_number 아래줄에 위치하는게 더 가독성이 좋지 않을까요?

2022-02-21 06:00 UTC, tanonkim commented on students/kihyeon/users/views.py
>                  first_name   = data["first_name"],
email, password를 여러번 사용하기 위해서 변수로 지정해줬는데 가독성 측면에서 한번 생각해봐야 할 것 같습니다!!

감사합니다😎

2022-02-21 06:09 UTC, sjoon21 reviewed
LGTM

2022-02-21 07:18 UTC, kyeongraekim requested changes
아래 내용 확인 하여 수정해주세요!~

2022-02-21 07:18 UTC, kyeongraekim commented on students/kihyeon/users/views.py
> +            hassed_password = secret_password.decode('utf-8')
- secret_password 라는 변수명은 보다 개발자 다운 표현은 아닌 것 처럼 보여지네요.
- hassed에 변수명 오타가 있어 보이네요~ 
- secret_password에 담겨진 내용이 실제로는 기현님이 아래 변수명에 기재하신 hash의 기능을 하고 있는 중입니다. 따라서 의미론 적으로 올바른 변수명 선언은 아니라고 보여집니다. 복잡하게 풀어나가실 필요없이 아래처럼 간단하게 풀어나가도 무방해보입니다!

- 다음의 내용 참고해주세요!~
```python
hashed_password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')

2022-02-21 07:29 UTC, tanonkim commented on students/kihyeon/users/views.py
> +            hassed_password = secret_password.decode('utf-8')
수정 완료했습니다!!☺️

2022-02-21 07:54 UTC, kyeongraekim requested changes
기현님 한가지 수정해 볼만한 내용 아래와 같이 제안드립니다. 한 번 보시고 어떻게 고쳐보면 좋을지 생각해보세요!~

2022-02-21 07:54 UTC, kyeongraekim commented on students/kihyeon/users/views.py
> +            phone_number    = data['phone_number']
- 기현님! phone_number 전화번호를 사용하지 않아도 되는, 즉 사용자가 전화번호를 회원 가입시 안 넣어도 되는 기획으로 한 번 모델링과 해당 뷰를 수정해보세요!~ abc['def']의 형식은 무조건 키에러를 내는 매핑 방법입니다. 무조건 키에러를 안내도 되는 파이썬 내의 메소드를 찾아서 적용해보세요!~

- 향후 프로젝트에서 꼭 쓰일 메소드이기 때문에 위스타그램에서의 선 경험을 추천드립니다~

2022-02-22 02:08 UTC, kyeongraekim requested changes
아래 내용 확인하여 수정해주세요!~

2022-02-22 02:08 UTC, kyeongraekim commented on students/kihyeon/users/views.py
> +            phone_number = data.get('phone_number', None)
- 현재 키매핑이 안될 시 제공되는 디폴트 값을 None 으로 주셨는데 장고 모델 설정 선에서 작동이 불가한 코드처럼 보이네요!~ 한 번 None 값이 들어가는게 가능한지 작동 확인을 해보셨을까요?

- 그리고 전화번호와 기타 정보에 대해서 다음의 링크를 확인한 후 blank, null에 대한 사용 여부에 대한 방향성을 한 번 고민해주세요!~
https://docs.djangoproject.com/en/4.0/ref/models/fields/#null

2022-02-22 02:34 UTC, tanonkim commented on students/kihyeon/users/views.py
> +            phone_number = data.get('phone_number', None)
모델과 뷰의 호환성까지는 미처 생각하지 못했습니다..!

경래님이 말씀하신 의도대로 수정해보았습니다☺️

2022-02-22 05:29 UTC, kyeongraekim approved these changes
LGTM!~

2022-02-22 05:30 UTC, kyeongraekim commented
컨플릭트 해결해주세요!~

2022-02-22 05:37 UTC, merged