[박건규] Mission 5: 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/30-westagram-backend-4-team pull request #24
Opened 2022-02-21 07:25 UTC by Pbang91

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입시 비밀번호 암호화 적용 코드 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- request로 받은 비밀번호 암호화 진행 후 decoding 진행 후 DB에 저장
- DB에 정상적으로 저장되는 것 확인
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
-  궁금한 사항을 DM으로 전달 드리겠습니다!

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-02-21 07:32 UTC, sjoon21 reviewed
LGTM

2022-02-21 07:37 UTC, tanonkim commented on students/geongue/users/views.py
> +            decoding_hashed_password = hashed_password.decode('utf-8')
너무 긴 변수명보다는 hashed_password라는 하나의 변수에 hash의 기능을 풀어나가도 될 것 같습니다!!

2022-02-21 07:59 UTC, kyeongraekim requested changes
아래 내용을 확인하여 수정 해주세요!~

2022-02-21 07:59 UTC, kyeongraekim commented on students/geongue/users/views.py
> +            decoding_hashed_password = hashed_password.decode('utf-8')
아래와 같은 방법으로 간단 명료하게 풀어나가는 것을 고민해보세요!~

```python
            hashed_password          = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')

2022-02-21 07:59 UTC, kyeongraekim commented on students/geongue/users/views.py
> +            phone                    = data['phone']
- phone 전화번호를 사용하지 않아도 되는, 즉 사용자가 전화번호를 회원 가입시 안 넣어도 되는 기획으로 한 번 모델링과 해당 뷰를 수정해보세요!~ abc['def']의 형식은 무조건 키에러를 내는 매핑 방법입니다. 무조건 키에러를 안내도 되는 파이썬 내의 메소드를 찾아서 적용해보세요!~
- 향후 프로젝트에서 꼭 쓰일 메소드이기 때문에 위스타그램에서의 선 경험을 추천드립니다~

2022-02-22 04:03 UTC, Pbang91 commented on students/geongue/users/views.py
> +            phone                    = data['phone']
해당 내용 dict 의 get 함수로 수정하였습니다!

2022-02-22 04:03 UTC, Pbang91 commented on students/geongue/users/views.py
> +            decoding_hashed_password = hashed_password.decode('utf-8')
참고하여 코드 수정 완료했습니다!

2022-02-22 06:38 UTC, kyeongraekim requested changes
아래 마이너 한 부분 마지막으로 수정해주세요!~

2022-02-22 06:38 UTC, kyeongraekim commented on students/geongue/users/views.py
> +            phone                    = data.get('phone', None)
phone 의 모델링 수정은 None(null) 값이 아닌 빈문자열, blank를 True로 해주신것 같아보이네요!
따라서 get 메소드의 디폴트값은 None이 아닌 "" 형태의 빈 문자열이 맞아 보입니다!~

2022-02-22 06:49 UTC, Pbang91 commented on students/geongue/users/views.py
> +            phone                    = data.get('phone', None)
수정 진행했습니다!

2022-02-22 07:36 UTC, kyeongraekim approved these changes
LGTM!~

2022-02-22 07:36 UTC, merged