[김산] Mission 5: 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/30-westagram-backend-4-team pull request #25
Opened 2022-02-21 07:36 UTC by cloudhat

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
-[김산] Mission 5: 회원가입 비밀번호 암호화 적용
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 입력받은 비밀번호를 암호화 함
- 암호화된 비밀번호를 DB에 저장
- 
## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-02-21 07:39 UTC, Pbang91 reviewed
LGTM !

2022-02-21 07:53 UTC, tanonkim commented on students/kimsan/users/migrations/0002_alter_user_password.py
> +# Generated by Django 4.0.2 on 2022-02-21 07:31
model 수정은 model을 위한 새로운 브랜치에서 commit하시는게 좋아보입니다!

2022-02-21 07:53 UTC, tanonkim commented on students/kimsan/users/views.py
> +import bcrypt
장고 컨벤션을 지켜야 할 것처럼 보입니다!

2022-02-21 07:53 UTC, tanonkim commented on students/kimsan/users/views.py
> +                password=hashed_password ,
사소한 것으로, 끝에 공백을 빼셔도 될 것 같습니다.
그리고 위코드 컨벤션을 지키면 더 가독성이 높은 코드가 될 것처럼 보입니다.

2022-02-21 08:02 UTC, kyeongraekim requested changes
아래 내용 확인 후 수정 및 기획변경에 대해 고민해보세요!~

2022-02-21 08:02 UTC, kyeongraekim commented on students/kimsan/users/views.py
> +
- phone_number 전화번호를 사용하지 않아도 되는, 즉 사용자가 전화번호를 회원 가입시 안 넣어도 되는 기획으로 한 번 모델링과 해당 뷰를 수정해보세요!~ abc['def']의 형식은 무조건 키에러를 내는 매핑 방법입니다. 무조건 키에러를 안내도 되는 파이썬 내의 메소드를 찾아서 적용해보세요!~
- 향후 프로젝트에서 꼭 쓰일 메소드이기 때문에 위스타그램에서의 선 경험을 추천드립니다~

2022-02-21 08:02 UTC, kyeongraekim commented on students/kimsan/users/views.py
> +                phone_number = phone_number)
맨 마지막 소괄호 엔터 한 번만 쳐주시면 더 깔끔해 보이겠네요!~

2022-02-21 08:39 UTC, cloudhat commented on students/kimsan/users/views.py
> +
get(key) 메소드를 이용하여 if-else 문을 제거하고 코드를  간결하게 수정했습니다.  
has_key 메소드를 고려해봤으나 python에서 지양하는 메소드라고 하여 사용하지 않았습니다.

2022-02-21 08:55 UTC, kyeongraekim requested changes
아래 추가 수정내용 반영해주세요!~

2022-02-21 08:55 UTC, kyeongraekim commented on students/kimsan/users/views.py
> +            phone_number = ''
제가 의도 드린 바에 맞게 잘 이해해주셨는데 사용 방법에 오류가 조금 보이네요~ 
현재 이부분은 빈문자열로 하드 코딩 된 것으로 보여집니다. 이곳에서 변수 선언을 올바르게 해주시고 아래 if 문에서 잘 활용해주세요!~

2022-02-21 08:55 UTC, kyeongraekim commented on students/kimsan/users/views.py
> +            if data.get('phone_number'):
위 내용이 잘 수정 반영된다면 이곳에서 2중 중첩의 조건절은 필요 없어 지게 될 것 같네요~

2022-02-21 09:39 UTC, cloudhat commented on students/kimsan/users/views.py
> +            if data.get('phone_number'):
아 알고보니 전화번호는 validation이 필요 없었네요. 빈 문자열이 validation 함수에 들어갔을 경우 예외처리를 하기 위해 이중 조건문을 사용했었습니다.
깔끔하게 수정했습니다!

2022-02-22 02:06 UTC, kyeongraekim requested changes
아래 내용 확인하여 수정해주세요!~

2022-02-22 02:06 UTC, kyeongraekim commented on students/kimsan/users/models.py
> +    extra_information = models.TextField(blank=True, null=True)
- 전화번호와 기타 정보에 대해서 다음의 링크를 확인한 후 blank, null에 대한 사용 여부를 다시 한 번 고민해주세요!~
- https://docs.djangoproject.com/en/4.0/ref/models/fields/#null

2022-02-22 04:03 UTC, cloudhat commented on students/kimsan/users/models.py
> +    extra_information = models.TextField(blank=True, null=True)
1. null 속성의 경우 unique와 blank 옵션이 둘 다 쓰여 '여러 빈 값' 넣어야 하는 상황을 제외하고는 지양해야 하는 속성임을 배웠습니다. https://www.notion.so/Null-vs-blank-field-option-db61fc427e544aa2ada6342d508012d4
2. 
2. key가 dictionary에 없을 경우 get메소드는 None(NULL)값을 반환하므로 26~27번째 줄에  phone_number에 할당된 None값을 빈 string으로 바꾸는 코드를 추가했습니다.

2022-02-22 04:09 UTC, cloudhat commented on students/kimsan/users/models.py
> +    extra_information = models.TextField(blank=True, null=True)
2. 앗 get 메소드에 반환값을 변경해줄 수 있었네요 ㅠ 만약 key값이 없을 경우 빈 string을 반환하도록 변경하였고 26~27번쨰 줄 코드는 삭제했습니다.

2022-02-22 05:27 UTC, kyeongraekim approved these changes
LGTM!~

2022-02-22 05:27 UTC, merged