[안성준] Mission 5: 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/30-westagram-backend-4-team pull request #26
Opened 2022-02-21 08:32 UTC by sjoon21

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 비밀번호 암호화 적용
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- bcrypt를 통해 hashed_password 생성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-02-21 08:35 UTC, tanonkim commented
LGTM🔥🔥🔥

2022-02-21 09:36 UTC, kyeongraekim requested changes
아래 내용 확인 후 수정해보세요!~

2022-02-21 09:36 UTC, kyeongraekim commented on students/sungjoon/users/views.py
> +            phone_number = data['phone_number']
- phone_number 전화번호를 사용하지 않아도 되는, 즉 사용자가 전화번호를 회원 가입시 안 넣어도 되는 기획으로 한 번 모델링과 해당 뷰를 수정해보세요!~ abc['def']의 형식은 무조건 키에러를 내는 매핑 방법입니다. 무조건 키에러를 안내도 되는 파이썬 내의 메소드를 찾아서 적용해보세요!~
- 향후 프로젝트에서 꼭 쓰일 메소드이기 때문에 위스타그램에서의 선 경험을 추천드립니다~

2022-02-22 01:32 UTC, sjoon21 commented on students/sungjoon/users/views.py
> +            phone_number = data['phone_number']
경래님, 현재 바꾼 코드  `phone_number = data.get('phone_number', None)`에서는 blank string이 허용이 됩니다. 하지만 다른분들은 models.py에 `blank = True`를 넣어서 바꾸었는데 view말고 models.py를 변형해야 하는 이유가 있을까요?

2022-02-22 02:03 UTC, kyeongraekim commented on students/sungjoon/users/views.py
> +            phone_number = data['phone_number']
- 다음의 링크 null 부분과 blank 부분을 공식문서를 통해 확인해 보시고 models.py 의 수정소요 여부를 한 번 확인해주세요!~
- https://docs.djangoproject.com/en/4.0/ref/models/fields/#null

2022-02-22 06:37 UTC, kyeongraekim requested changes
아래 내용의 마이너한 부분 수정 반영해주세요!~

2022-02-22 06:37 UTC, kyeongraekim commented on students/sungjoon/users/views.py
> +            phone_number = data.get('phone_number', None)
phone_number 의 모델링 수정은 None(null) 값이 아닌 빈문자열, blank를 True로 해주신것 같아보이네요! 
따라서 get 메소드의 디폴트값은 None이 아닌 "" 형태의 빈 문자열이 맞아 보입니다!~

2022-02-22 06:42 UTC, sjoon21 commented on students/sungjoon/users/views.py
> +            phone_number = data.get('phone_number', None)
확인했습니다! 감사합니다 경래님

2022-02-22 07:35 UTC, kyeongraekim approved these changes
LGTM!~

2022-02-22 07:35 UTC, merged