[박건규] Mission 6: 로그인 JWT 발급
wecode-bootcamp-korea/30-westagram-backend-4-team pull request #31
Opened 2022-02-22 08:57 UTC by Pbang91

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- JWT 토큰 기능 추가 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 로그인 성공 시 JWT 토큰 반환
- 실패시 에러반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
-  

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-02-22 09:12 UTC, sjoon21 commented on students/geongue/users/views.py
> +            access_token   = jwt.encode({'user_id' : users.id}, SECRET, ALGORITHM)
건규님, ` SECRET = SECRET_KEY` 부분과 `ALGORITHM = algorithm` 부분이 불필요해보입니다.  SECRET_KEY와 algorithm을  따로 변수로 만드신 이유가 있을까요?

2022-02-22 09:48 UTC, Pbang91 commented on students/geongue/users/views.py
> +            access_token   = jwt.encode({'user_id' : users.id}, SECRET, ALGORITHM)
클래스 내에서 따로 표현을 해주고 싶었는데, 고쳐서 진행하겠습니다 :)

2022-02-22 10:14 UTC, kyeongraekim requested changes
아래 내용 확인 후 수정해주세요!~

2022-02-22 10:14 UTC, kyeongraekim commented on students/geongue/users/views.py
> +            users          = User.objects.get(email = login_email)
해당 부분이 아래 이메일 검증 부분보다 먼저 선언되면 Model.DoesNotExist 문제가 발생할 것 같네요. 곰곰히 어떤 기획으로 진행할지 고민해보세요!~

2022-02-22 10:14 UTC, kyeongraekim commented on students/geongue/users/views.py
> +            access_token   = jwt.encode({'user_id' : users.id}, SECRET_KEY, algorithm)
환경변수는 상수 데이터이기 때문에 대문자 네이밍 컨벤션을 지켜주세요!

2022-02-22 10:14 UTC, kyeongraekim commented on students/geongue/users/views.py
> +            users          = User.objects.get(email = login_email)
쿼리 셋이 아닌 단 하나의 유저객체만 잡을 메소드이기 때문에 users 복수 표현은 옳지 않아 보입니다.

2022-02-22 10:59 UTC, Pbang91 commented on students/geongue/users/views.py
> +            users          = User.objects.get(email = login_email)
이메일 검증부분을 위로 올리고 선언을 아래로 내렸습니다. 감사합니다!

2022-02-22 10:59 UTC, Pbang91 commented on students/geongue/users/views.py
> +            users          = User.objects.get(email = login_email)
변수명을 user로 변경했습니다!

2022-02-22 11:00 UTC, Pbang91 commented on students/geongue/users/views.py
> +            access_token   = jwt.encode({'user_id' : users.id}, SECRET_KEY, algorithm)
ALGORITHM 으로 변경했습니다!

2022-02-22 12:24 UTC, kyeongraekim requested changes

2022-02-22 12:24 UTC, kyeongraekim commented on students/geongue/westagram/settings.py
> +algorithm = "HS256"
settings.py 는 깃헙에 올라올 부분이기때문에 해당 알고리즘은 환경변수화해서 my_settings.py 에서 대문자 변수명에 담아서 처리해주세요!~

2022-02-22 12:32 UTC, Pbang91 commented on students/geongue/westagram/settings.py
> +algorithm = "HS256"
죄송합니다....삭제했습니다...

2022-02-23 01:21 UTC, kyeongraekim approved these changes
LGTM!~

2022-02-23 01:22 UTC, merged

2022-02-23 01:24 UTC, kyeongraekim commented
네 건규님 PR양식을 통해서 잘 고민해주신 것 같네요!~ 저러한 보안상의 이유도 있지만 의존성의 이유에서도 해당 내용이 settings.py를 바라보면 좋습니다. 왜냐하면 수 많은 파일과 코드들의 향연일 실제 웹 서비스에서 환경변수의 변화가 생기게 된다면 실제 import 하고 있는 수 많은 views 파일들에 일일이 들어가서 모든 것을 수정해야 하는 문제가 생기기 때문이죠!  "의존성" 이라는 키워드로  한 번 또 리서치 해보시는 것을 추천드립니다!~